name: Deploy Cloudflare Worker
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # This tells the setup-node action to cache npm dependencies

      - name: Install dependencies
        run: npm ci --include=optional

      - uses: actions/checkout@v3
      - name: Deploy
        working-directory: packages/worker  # Specifies the directory where the npm command should be run
        # run npx wrangler publish
        run: npm ci --include=optional && CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} npx wrangler deploy